config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "matches#index"
  resources :matches, only: [:index, :show] do
  resources :comments, only: [:create]
    resources :odds, only: [:show, :create, :new] do
      resources :bookings, only: [:create]
    end
  end

  get "/dashboard", to: "users#dashboard"
  get "/about", to: "pages#index"
end

app/views/shared/_card.html.erb
<%= link_to match_path(match) do  %>
  <div class="card">
    <div class="card-teams">
      <div class="left-team">
        <% if match.home_logo %>
          <% photo =  match.home_logo %>
        <% else %>
          <% photo =  "logo.png" %>
        <% end %>
        <%= image_tag photo, class:"team-logo" %>
        <h5><%= match.home_team %></h5>
        <p class="t-shadow"><%= match.goals_home_team %></p>
      </div>
        <span class="t-shadow">VS</span>
      <div class="right-team">
      <% if match.away_logo %>
          <% photo = match.away_logo %>
        <% else %>
          <% photo =  "logo.png" %>
        <% end %>
        <%= image_tag photo, class:"team-logo" %>
        <h5><%= match.away_team %></h5>
        <p class="t-shadow"><%= match.goals_away_team %></p>
      </div>
    </div>

    <div class="card-date">
      <span><%= match.match_date.strftime('%b %e, %l:%M %p') %></span>
    </div>

  <p class="status"><%= match.status %></p>
  </div>
<% end %>

app/views/shared/_dashboard_bookings_container.html.erb
<% user_bookings.each do |booking| %>
  <%= render 'shared/dashboard_messages', booking: booking, bet_outcome: booking.won? %>
<% end %>

app/views/shared/_dashboard_messages.html.erb
<div class="message <%= bet_outcome %>">
  <div class="message-body cards-team">
        <div class="team home-team">
          <%= image_tag booking.odd.match.home_logo ? booking.odd.match.home_logo : "logo.png", class:"team-avatar" %>
          <span><%= booking.odd.match.home_team %></span>
        </div>
        <div class="team away-team">
          <%= image_tag booking.odd.match.away_logo ? booking.odd.match.away_logo : "logo.png", class:"team-avatar" %>
          <span><%= booking.odd.match.away_team %></span>
        </div>
  </div>

  <div class="message-body score">
    <% if booking.odd.match.status == "FINISHED" %>
    <div class="team home-team">
      <h4><%= booking.odd.match.goals_home_team %></h4>
    </div>
    <div class="team away-team">
      <h4><%= booking.odd.match.goals_away_team %></h4>
    </div>
    <% end %>
  </div>

  <div class="message-body" id="stake">
    <% if booking.odd.match.status == "FINISHED" %>
      <%= render 'users/finished_body', booking: booking %>
    <% else %>
      <%= render 'users/pending_body', booking: booking %>
    <% end %>
  </div>

  <div class="message-status">
    <div class="message-date text-center">
      <% date = booking.odd.match.match_date %>
      <p class="date"><%= date.strftime('%b %e') %></p>
      <p class="date"><%= date.strftime('%l:%M %p') %></p>
    </div>
  </div>

  <div class="avatar-container">
    <% creator = booking.odd.user %>
    <%= image_tag creator.facebook_picture_url ? creator.facebook_picture_url : "https://api.adorable.io/avatars/285/#{creator.email}.png", class: "creator-avatar" %>
    <div class="hover-box">
        <h6 class="text-center"><%= creator.user_name %></h6>
        <p><span class="title">won:  </span><span class="won"><%= creator.calculate_created_odds_won %></span></p>
        <p><span class="title">lost:  </span><span class="lost"><%= creator.calculate_created_odds_lost %></span></p>
    </div>
  </div>
</div>

app/views/shared/_dashboard_sold_odds_container.html.erb
<%  @created_odds.each do |odd|%>
  <%= render 'users/owned_odds', odd: odd, bet_outcome: odd.won? %>
<% end %>

app/views/shared/_dashboard_tab.html.erb
<div class="match-tabs">
  <a class="tab active" data-target="#all">
    <h3>All</h3>
  </a>
  <a class="tab" data-target="#home">
    <h3>Win</h3>
  </a>
  <a class="tab" data-target="#draw">
    <h3>Lost</h3>
  </a>
  <a class="tab" data-target="#away">
    <h3>Pending</h3>
  </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/tommylees112/match-market"><i class="fa fa-github"></i></a>
    <a href="https://www.instagram.com/lewagonlondon/"><i class="fa fa-instagram"></i></a>
    <a href="https://www.facebook.com/lewagonlondon/"><i class="fa fa-facebook"></i></a>
    <a href="https://twitter.com/lewagonlondon"><i class="fa fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/5046700/"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_match_show_head.html.erb
<div class="">
  <div class="match-header">
      <div class="col-xs-3">
        <div class="team-icon">
          <% if @match.home_logo %>
            <% photo = @match.home_logo %>
          <% else %>
            <% photo = "logo.png" %>
          <% end %>
          <%= image_tag photo, class:"team-logo" %>
        </div>
      </div>
      <div class="col-xs-2">
        <div class="vs text-center">
          <h2>VS</h2>
        </div>
      </div>
      <div class="col-xs-3">
        <div class="team-icon">
          <% if @match.away_logo %>
            <% photo = @match.away_logo %>
          <% else %>
            <% photo = "logo.png" %>
          <% end %>
          <%= image_tag photo, class:"team-logo" %>
        </div>
      </div>
  </div>
  <div class="match-date text-center">
    <% date = @match.match_date %>
     <%= date.strftime("%A, %B %e, %l:%m %p") %>
  </div>
</div>

app/views/shared/_match_tab.html.erb
<div class="match-tabs">
  <a class="tab active" data-target="#all">
    <h3>All</h3>
  </a>
  <a class="tab" data-target="#home">
    <h3>Home</h3>
  </a>
  <a class="tab" data-target="#draw">
    <h3>Draw</h3>
  </a>
  <a class="tab" data-target="#away">
    <h3>Away</h3>
  </a>
</div>

app/views/shared/_modal.html.erb
<div id="makeOdd" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create Your Own Odds</h4>
        <h3><%= @match.home_team %> v. <%= @match.away_team %></h3>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@match, @odd] do |f| %>
          <%= f.label :odd_outcome, '<abbr title="required">*</abbr> Outcome'.html_safe %>

          <%= f.input :outcome, collection: Odd::VALUES, as: :radio_buttons, label: false, item_label_class: "radio-inline", item_wrapper_tag: false %>
          <%= f.input :odds %>
          <%= f.input :max_people, collection: 0..10, prompt: "Select the number of people who can buy this bet", selected: 1%>
          <%= f.submit %>
        <% end %>
      </div>

    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-colour.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "About", about_path, class:"navbar-about" %>
      <%= link_to root_path, class: "navbar-wagon-item navbar-wagon-link" do %>
        <span>Home</span>
      <% end %>
      <%= link_to "Profile", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% avatar_url = current_user.facebook_picture_url || "https://api.adorable.io/avatars/285/#{current_user.email}.png" %>
          <div class="avatar dropdown-toggle" style="background-image: url(<%= image_path avatar_url %>);" id="navbar-wagon-menu" data-toggle="dropdown">

          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "About", about_path, class:"navbar-about" %>
      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href=<%= root_path %>><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
        <li><a href=<%= dashboard_path %>><i class="fa fa-user" aria-hidden="true"></i> Profile</a></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_odd_modal.html.erb
<div id="makeBet<%= normal_id ? odd_selected.id : "#{odd_selected.id}id" %>" class="modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Make this Bet:</h4>
        <h4><%= @match.home_team %> v. <%= @match.away_team %></h4>
        <h3><%= odd_selected.outcome.capitalize %></h3>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@match, odd_selected, @booking] do |f| %>
          <%= f.label 'Stake:' %>
          <%= f.input :stake, label: false, input_html: { min: '0', step: 'any' }  do %>
          <%= content_tag :span, "£", class: "add-on" %>
          <%= f.number_field :stake %>
          <%= f.submit 'Make Bet', input_html: { class: "align-right" } %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/shared/_tabs.html.erb
<div class="tabs">
  <div class="tabs-img">
    <a class="fixture_tab active" data-target="#premiership" data-week="3">
    <%= image_tag "premier.png" %>
    </a>
    <a class="fixture_tab" data-target="#bundesliga" data-week="2">
    <%= image_tag "bundes.png" %>
    </a>
    <a class="fixture_tab" data-target="#laliga" data-week="2">
    <%= image_tag "laliga.png" %>
    </a>
    <a class="fixture_tab" data-target="#serieA" data-week="2">
      <%= image_tag "seriea.png" %>
    </a>
    <a class="fixture_tab" data-target="#ligue1" data-week="4">
      <%= image_tag "ligue1.png" %>
    </a>
  </div>
</div>

app/views/shared/_week_toggle.html.erb
<div class="fixtures_pager">
  <div class="week_button btn btn-primary previous" id="previous">
    <i class="fa fa-arrow-left"></i> Previous
  </div>
  <div class="week_details text-center">
    <div>
      <%= league %>
    </div>
    <div>
    <h3>Game Week: <%= game_week %></h3>
    </div>
  </div>
  <div class="week_button btn btn-primary next" id="next">
    Next <i class="fa fa-arrow-right"></i>
  </div>
</div>