config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "matches#index"
  resources :matches, only: [:index, :show] do
  resources :comments, only: [:create]
    resources :odds, only: [:show, :create, :new] do
      resources :bookings, only: [:create]
    end
  end

  get "/dashboard", to: "users#dashboard"
  get "/about", to: "pages#index"
end

app/models/match.rb
class Match < ApplicationRecord
  paginates_per 15
  has_many :odds
  has_many :bookings, through: :odds
  has_many :comments
  validates :home_team, presence: true
  validates :away_team, presence: true
  validates :match_date, presence: true
  validates :gameweek, presence: true, numericality: true
  validates :league, presence: true

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  skip_before_action :authenticate_user!

  def index


   if params[:search].present?
    # @matches = Match.where('home_team LIKE ? OR away_team LIKE ?, "%#{params[:search].downcase}%", "%#{params[:search].downcase}%"')
    @premiership_matches = Match.where('lower(home_team) LIKE ? or lower(away_team) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").order(:match_date)
    @bundesliga_matches = Match.where('lower(home_team) LIKE ? or lower(away_team) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").order(:match_date)
    @laliga_matches = Match.where('lower(home_team) LIKE ? or lower(away_team) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").order(:match_date)
    @ligue1_matches = Match.where('lower(home_team) LIKE ? or lower(away_team) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").order(:match_date)
    @serieA_matches = Match.where('lower(home_team) LIKE ? or lower(away_team) LIKE ?', "%#{params[:search].downcase}%", "%#{params[:search].downcase}%").order(:match_date)
    else
    @premiership_matches = Match.where(league: "Premier League 2017/18").order(:match_date)
    @bundesliga_matches = Match.where(league: "Bundesliga 2017/18").order(:match_date)
    @laliga_matches = Match.where(league: "La Liga 2017/18").order(:match_date)
    @ligue1_matches = Match.where(league: "Ligue 1 2017/18").order(:match_date)
    @serieA_matches = Match.where(league: "Serie A 2017/18").order(:match_date)
   end


  end



  def show
    @match = Match.find(params[:id])
    @odd = Odd.new
    @booking = Booking.new
    @comment = Comment.new
    @all_odds = @match.odds.all.order(:odds)
    @home_odds = @match.odds.where(outcome: "Home").order(:odds)
    @away_odds = @match.odds.where(outcome: "Away").order(:odds)
    @draw_odds = @match.odds.where(outcome: "Draw").order(:odds)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/index.html.erb
<% content_for :title, "Match Market"   %>


<div class="banner">
  <div class="banner-content">
    <h1>Be the Bookie</h1>
    <p>make your own luck</p>

</div>
<div class="test1">
  <!-- <div class="search_form"> -->
  <%= form_tag(matches_path, method: 'get', class:"new_form form-inline") do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag("Search", name: nil, class:"btn btn-primary searchbtn") %>
  <% end %>
</div>
  <!-- </div> -->
</div>

<%= render 'shared/tabs' %>
<div class="index-card-container">

      <div class="fixtures active" id="premiership" data-target=".premiership">
        <% for game_week in (1..38).to_a %>
          <div id=<%= "game_week#{game_week}" %> class="gameweek_fixtures premiership">
            <% league = @premiership_matches.first.league %>
            <%= render 'shared/week_toggle', game_week: game_week, league: league %>
            <div class="row">
            <% @premiership_matches.select{|filter_match| filter_match.gameweek == game_week}.each do |match| %>
                <div class="col-xs-12 col-sm-6 col-md-4">
                  <%= render 'shared/card', match: match %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>


      <div class="fixtures" id="bundesliga" data-target=".bundesliga">
        <% for game_week in (1..34).to_a %>
          <div id=<%= "game_week#{game_week}" %> class="gameweek_fixtures bundesliga">
        <% league = @bundesliga_matches.first.league %>
        <%= render 'shared/week_toggle', league: league, game_week: game_week %>
            <div class="row">
            <% @bundesliga_matches.select{|filter_match| filter_match.gameweek == game_week}.each do |match| %>
                <div class="col-xs-12 col-sm-6 col-md-4">
                  <%= render 'shared/card', match: match %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>


      <div class="fixtures" id="laliga" data-target=".laliga">
        <% for game_week in (1..38).to_a %>
          <div id=<%= "game_week#{game_week}" %> class="gameweek_fixtures laliga">
        <% league = @laliga_matches.first.league %>
        <%= render 'shared/week_toggle', league: league, game_week: game_week %>
            <div class="row">
            <% @laliga_matches.select{|filter_match| filter_match.gameweek == game_week}.each do |match| %>
                <div class="col-xs-12 col-sm-6 col-md-4">
                  <%= render 'shared/card', match: match %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="fixtures" id="ligue1" data-target=".ligue1">
        <% for game_week in (1..38).to_a %>
          <div id=<%= "game_week#{game_week}" %> class="gameweek_fixtures ligue1">
        <% league = @ligue1_matches.first.league %>
        <%= render 'shared/week_toggle', league: league, game_week: game_week %>
            <div class="row">
            <% @ligue1_matches.select{|filter_match| filter_match.gameweek == game_week}.each do |match| %>
                <div class="col-xs-12 col-sm-6 col-md-4">
                  <%= render 'shared/card', match: match %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="fixtures" id="serieA" data-target=".serieA">
        <% for game_week in (1..38).to_a %>
          <div id=<%= "game_week#{game_week}" %> class="gameweek_fixtures serieA">
        <% league = @serieA_matches.first.league %>
        <%= render 'shared/week_toggle', league: league, game_week: game_week %>
            <div class="row">
            <% @serieA_matches.select{|filter_match| filter_match.gameweek == game_week}.each do |match| %>
                <div class="col-xs-12 col-sm-6 col-md-4">
                  <%= render 'shared/card', match: match %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

</div>

app/views/matches/show.html.erb
<% content_for :title, "Odds"   %>

<div class="match_page">

  <div class="match-info">
      <%= render "shared/match_show_head" %>
      <div class="flex-center make-odd-button" style="width: 100%">
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#makeOdd">Make Odd</button>
      </div>
      <%= render 'shared/modal' %>
      <%= render "shared/match_tab" %>


        <div class="odds active" id="all">
            <div class="row">
              <% @all_odds.each do |odd| %>
                <div class="col-xs-6 col-sm-4">
                  <%= render "odds/odds_cards", odd: odd, normal_id: false %>
                </div>
              <% end %>
            </div>
        </div>
        <div class="odds" id="home">
            <div class="row">
              <% @home_odds.each do |odd| %>
                <div class="col-xs-6 col-sm-4">
                  <%= render "odds/odds_cards", odd: odd, normal_id: true %>
                </div>
              <% end %>
            </div>
        </div>
        <div class="odds" id="away">
            <div class="row">
              <% @away_odds.each do |odd| %>
                <div class="col-xs-6 col-sm-4">
                  <%= render "odds/odds_cards", odd: odd, normal_id: true %>
                </div>
              <% end %>
            </div>
        </div>
        <div class="odds" id="draw">
            <div class="row">
              <% @draw_odds.each do |odd| %>
                <div class="col-xs-6 col-sm-4">
                  <%= render "odds/odds_cards", odd: odd, normal_id: true %>
                </div>
              <% end %>
            </div>
        </div>

  </div>

  <div class="comment_board">
    <div class="comment_header">
      <h2>Comments:</h2>
    </div>
    <div class="comments_list" id="comments_list">
      <% @match.comments.reverse.each do |comment| %>
        <%= render 'comments/comment_show', comment: comment, booking: @booking %>
      <% end %>
    </div>
    <div class="comment_form" id="comment_form">
      <%= render 'comments/form', match: @match, comment: @comment %>
    </div>
  </div>
</div>